apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: file-storage
  name: file-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-storage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: file-storage
    spec:
      containers:
        - args:
            - server
            - --address
            - 0.0.0.0:9000
            - --console-address
            - 0.0.0.0:9001
            - /data
          env:
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: file-storage-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_ROOT_USER
              valueFrom: 
                configMapKeyRef:
                  name: file-storage-configmap
                  key: MINIO_ROOT_USER
          image: quay.io/minio/minio
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:9000/minio/health/live
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 20
          name: file-storage
          ports:
            - containerPort: 9000
            - containerPort: 9001
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: file-storage-claim0
      restartPolicy: Always
      volumes:
        - name: file-storage-claim0
          persistentVolumeClaim:
            claimName: file-storage-claim0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: file-storage
  name: file-storage
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  type: NodePort
  selector:
    app: file-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: file-storage-claim0
  name: file-storage-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
