apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_BROKER_ID
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_INTER_BROKER_LISTENER_NAME
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: KAFKA_ZOOKEEPER_CONNECT
          image: confluentinc/cp-kafka:latest
          name: kafka
          ports:
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  type: NodePort