apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - env:
            - name: DB_ADDR
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_ADDR
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: POSTGRES_DB
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: POSTGRES_PASSWORD
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: POSTGRES_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: POSTGRES_USER
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_VENDOR
            - name: KEYCLOAK_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: KEYCLOAK_IMPORT
            - name: KEYCLOAK_LOGO
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: KEYCLOAK_LOGO
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KEYCLOAK_PASSWORD
            - name: KEYCLOAK_USER
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: KEYCLOAK_USER
            - name: PROXY_ADDRESS_FORWARDING
              valueFrom:
                configMapKeyRef:
                  name: keycloak-configmap
                  key: PROXY_ADDRESS_FORWARDING
          image: dockerhub/sunbird-rc-keycloak:latest
          livenessProbe:
            exec:
              command:
                 ["curl", "-f", "http://localhost:8080/"]
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: keycloak
          ports:
            - containerPort: 8080
            - containerPort: 9990
          resources: {}
          volumeMounts:
            - mountPath: /opt/jboss/keycloak/imports
              name: keycloak-claim0
      restartPolicy: Always
      volumes:
        - name: keycloak-claim0
          persistentVolumeClaim:
            claimName: keycloak-claim0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    # - name: "9990"
    #   port: 9990
    #   targetPort: 9990
  selector:
    app: keycloak
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: keycloak-claim0
  name: keycloak-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
