apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: dockerhub/sunbird-rc-nginx
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - localhost:80
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  type: NodePort
  selector:
    app: nginx